sync_topics: ['/vicon/Modquad1/odom',
  '/vicon/Modquad2/odom',
  '/mavros1/mocap/pose',
  '/mavros2/mocap/pose',
  '/mavros1/Imu/data',
  '/mavros2/Imu/data',
  '/whycon/poses',
  #'/whycon/image_out',
  '/modquad1/filtered_Vision_Odom']
ignore_nodes: ['']
ignore_services: ['']
